export const enum SkillNames {
    BladesIntuition = "Blade's Intuition",
    Cloak = "Cloak",
    CybersEdge = "Cyber's Edge",
    Datamancer = "Datamancer",
    DigitalObserver = "Digital Observer",
    EvasiveSystem = "Evasive System",
    HandsOfMidas = "Hands of Midas",
    Hyperdrive = "Hyperdrive",
    Marksman = "Marksman",
    Reaper = "Reaper",
    Overclock = "Overclock",
    ShortCircuit = "Short-Circuit",
    Tact = "Tact",
    Tracer = "Tracer",
    WeaponProficiency = "Weapon Proficiency",
}
