name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run lint

  typescript:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npx tsc
