name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: jest
        run: npm run test

      - name: eslint
        run: npm run lint

      - name: typescript
        run: npx tsc
